FROM multiarch/debian-debootstrap:armhf-stretch

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update

# sensible-build.sh deps and deb packing debs
RUN apt-get install -y --no-install-recommends \
       git ca-certificates wget patch \
       build-essential debhelper dpkg-dev \
       devscripts equivs

# build dpes
RUN apt-get install -y --no-install-recommends \
       debhelper tcl8.6-dev autoconf python3-dev python3-venv libz-dev dh-systemd openssl

# runtime deps
RUN apt-get install -y --no-install-recommends \
       net-tools iproute2 tclx8.4 tcl8.6 tcllib tcl-tls itcl3
